version: 2
 
sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
    - name: lineitems
    - name: suppliers 
    - name: parts
    - name: partsupps
    - name: customers      
    - name: nations
    - name: regions
      columns:
        - name: r_name
          tests:
            - accepted_values:
               values: ['ASIA','AFRICA','AMERICA','EUROPE']
               schema: SCH_ERROR
    - name: orders
      loaded_at_field: o_orderdate::timestamp
      freshness:
        warn_after: {count: 1, period: day}
        error_after: {count: 2, period: day}